version: '3'

services:
  redis:
    image: "redis"
    volumes:
      - ./data:/data
  airy-canvas-mini:
    image: "you06/airy-canvas-mini"
    ports:
      - "3333:3000"
    depends_on:
      - redis
    command:
      - yarn
      - start
      - -r
      - redis
