version: '3'

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.100.0/24"

services:
  redis:
    image: "redis"
    networks:
      app_net:
        ipv4_address: 172.16.100.5
    volumes:
      - "data:/data"
  airy-canvas-mini:
    image: "you06/airy-canvas-mini"
    networks:
      app_net:
        ipv4_address: 172.16.100.10
    depends_on:
      - redis
    command:
      - yarn
      - start
      - -r
      - redis

volumes:
  data:
